import 'package:firebase_core/firebase_core.dart';

/// Replace the placeholder values with the configuration generated by
/// `flutterfire configure`. Keeping the file in source control simplifies
/// onboarding for new developers because the API mirrors the default file
/// generated by FlutterFire.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
  apiKey: "AIzaSyByz5A7IH7tdMWsOwKB1wGHpYyflXbs__g",
  authDomain: "wajeeh-app-b0c2b.firebaseapp.com",
  databaseURL: "https://wajeeh-app-b0c2b-default-rtdb.firebaseio.com",
  projectId: "wajeeh-app-b0c2b",
  storageBucket: "wajeeh-app-b0c2b.firebasestorage.app",
  messagingSenderId: "525840946526",
  appId: "1:525840946526:web:e238940ac89200e00debcf"  
  
    );
  }
}
